## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)
sudo: required
language: c

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
## Save ENV dir
- cd ../
- export ENV_DIR=$(pwd)

install:
## Dependencies
- sudo apt-get install -yqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev

before_script:
## Make cleanup, just for prevent anything
- cd ${ENV_DIR}/
- rm -rf ${ENV_DIR}/gsKit/ ${ENV_DIR}/ps2eth/ ${ENV_DIR}/ps2toolchain/ ${ENV_DIR}/ps2-packer/ ${ENV_DIR}/ps2sdk-ports/

## Set up some variables
- export PS2DEV=${ENV_DIR}/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
- export PS2ETH=${PS2DEV}/ps2eth
- export GSKIT=${PS2DEV}/gsKit
- export LANG=C
- export LC_ALL=C

## Clone all
- cd ${ENV_DIR}/
- git clone --quiet https://github.com/ps2dev/ps2toolchain.git ${ENV_DIR}/ps2toolchain/
- git clone --quiet https://github.com/ps2dev/ps2sdk-ports.git ${ENV_DIR}/ps2sdk-ports/
- git clone --quiet https://github.com/ps2dev/ps2eth ${ENV_DIR}/ps2eth/
- git clone --quiet https://github.com/ps2dev/gsKit.git ${ENV_DIR}/gsKit/
- git clone --quiet https://github.com/ps2dev/ps2-packer.git ${ENV_DIR}/ps2-packer/
- chmod +x $(find . -name \*sh)

## ps2dev/PS2Toolchain
- cd ${ENV_DIR}/ps2toolchain/
- bash ./toolchain.sh

## ps2dev/PS2SDKPorts/zlib
- cd ${ENV_DIR}/ps2sdk-ports/zlib/
- make; make install

## ps2dev/PS2SDKPorts/libpng
- cd ${ENV_DIR}/ps2sdk-ports/libpng/
- make; make install

## ps2dev/PS2SDKPorts/libjpeg
- cd ${ENV_DIR}/ps2sdk-ports/libjpeg/
- make; make install

## ps2dev/PS2SDKPorts/freetype
- cd ${ENV_DIR}/ps2sdk-ports/freetype-2.4.12/
- bash ./SetupPS2.sh

## ps2dev/PS2ETH
- cd ${ENV_DIR}/ps2eth/
- make
- sudo mkdir -p /usr/lib/ps2dev/ps2eth
- sudo tar c $(find . -name \*irx) | sudo tar x -C /usr/lib/ps2dev/ps2eth

## ps2dev/gsKit
- cd ${ENV_DIR}/gsKit/
- make; make install

## ps2dev/PS2Packer
- cd ${ENV_DIR}/ps2-packer/
- make; make install

script:
## Let's build Open PS2 Loader Release!
- cd ${TRAVIS_BUILD_DIR}/
- make release
- bash ./lng_pack.sh

before_deploy:
- export TRAVIS_OPL_VERSION=$(make oplversion)
- export TRAVIS_CURRENT_DATE=$(date +"%d%m%y")
- export GIT_TAG=${TRAVIS_OPL_VERSION}-NIGHTLY-${TRAVIS_CURRENT_DATE}-${TRAVIS_BUILD_NUMBER}
- git tag ${GIT_TAG} -a -m "Generated tag from TravisCI for build ${TRAVIS_OPL_VERSION}-NIGHTLY-${TRAVIS_CURRENT_DATE}-${TRAVIS_BUILD_NUMBER}"
- git push -q https://${TAGPERM}@github.com/${TRAVIS_REPO_SLUG} -f --tags

## [TEMPLATE] Deploy OPL to Github Releases
# 1. Clone this repository
# 2. Copy '.travis.yml' to '.travis-original.yml' (you will need it after)
# 3. Install Travis Client <https://github.com/travis-ci/travis.rb#installation>
# 4. Run command: $(travis setup releases)
#    After follow all previous steps, pickup ONLY the "secure" line
#    and change it on '.travis-original.yml'
# 5. Move '.travis-original.yml' to '.travis.yml'
# 6. Commit it
## NOTE: You need to configure TravisCI before anything <https://travis-ci.org/>

## Deploy OPL to Github Releases
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZypQ3FMePwUO0JhqqoArINfVK7EWE5hbXF9FehajlNWeJ/AxOeL0QMdO0kzt80exZkh5DYuqc0Pbla5ZM9eZkuKFQkeGUNR06j+JNMWKJD5VbcfHxWy+3vUwJWVQR/D2nFERdBa4WM1CEEn2cCL7PR8Yxiu9jlF1D/QdoM2vMvAHrBFRdvVuUDeO63QtLzQvOuuEhYvwygk25sS2vIE8Jb67bbj/hjhdUE/a9AK9RDCErmBwARijz79QDfvahut7nxQO7TRKvb04D+3ZJGpCsfdV02sqc4G7Gez+qtChU/ILwIXWiHnR40ZFcf4bq6PE2qWpr6Mh319eNaiek6MY42packupz2D8wO0AHm6nsFjBXksAo3ndpqdDweW1nGxBYBXJBYoKZ5LTMo4l0yNDnTCHeMY+JhTI1/NogZacOBjbFLEogu2nfVLbCSqszcm6F2S9dX9ZgzSD98JXQQjpo4eiMvqVkKd7MhmROOea6071zBTVBwdBILjf2v8AIENlP0vq16JAQlJ+kYq4jbX9fcwobyquMEzRlzxuCVjQJRShqAS33PUPcU4TuL2n70xiCu9Vwo+9N9LtbQ/QPHmEQzytsAlvMel2xcyqRH0IROT+Gvt/gIomsvWOfhNAWT6aFSAz3Henc/QGCkt1JmuG9OHqVo3Qyqd2lAaoj2rw1j4=
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/OPNPS2LD-*.zip"
    - "${TRAVIS_BUILD_DIR}/OPNPS2LD_LANGS-*.zip"
  on:
    branch: master
